const TRANSACTIONS_DASHBOARD_DELETE_TRANSACTION_TITLE =
  'transactions-dashboard-delete-transacation.title';
const TRANSACTIONS_DASHBOARD_DELETE_TRANSACTION_MESSAGE =
  'transactions-dashboard-delete-transacation.message';
const TRANSACTIONS_DASHBOARD_DELETE_TRANSACTION_BUTTON_CONFIRM_TITLE =
  'transactions-dashboard-delete-transacation.button-confirm-title';
const TRANSACTIONS_DASHBOARD_DELETE_TRANSACTION_BUTTON_ABORT_TITLE =
  'transactions-dashboard-delete-transacation.button-abort-title';
const TRANSACTIONS_DASHBOARD_MODAL_TITLE = 'transactions-dashboard-modal-title';
const TRANSACTIONS_DASHBOARD_TITLE = 'transactions-dashboard-title';

export default {
  TRANSACTIONS_DASHBOARD_DELETE_TRANSACTION_TITLE,
  TRANSACTIONS_DASHBOARD_DELETE_TRANSACTION_MESSAGE,
  TRANSACTIONS_DASHBOARD_DELETE_TRANSACTION_BUTTON_CONFIRM_TITLE,
  TRANSACTIONS_DASHBOARD_DELETE_TRANSACTION_BUTTON_ABORT_TITLE,
  TRANSACTIONS_DASHBOARD_MODAL_TITLE,
  TRANSACTIONS_DASHBOARD_TITLE,
};
